---
abstract: 'formerly PerL Awesome SHell, Yeeeeaaaaaa!'
author:
  - 'GomoR <gomor_at_metabrik.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Metabrik
provides:
  CPAN::Class::Gomor:
    file: lib/CPAN/Class/Gomor.pm
    version: '1.02'
  CPAN::Class::Gomor::Hash:
    file: lib/CPAN/Class/Gomor/Hash.pm
    version: '1.02'
  CPAN::Data::Dump:
    file: lib/CPAN/Data/Dump.pm
    version: '1.22'
  CPAN::Lexical::Persistence:
    file: lib/CPAN/Lexical/Persistence.pm
    version: '1.020'
  CPAN::Module::Reload:
    file: lib/CPAN/Module/Reload.pm
    version: '1.08'
  Metabrik:
    file: lib/Metabrik.pm
    version: 1.00_04
  Metabrik::Brik:
    file: lib/Metabrik/Brik.pm
  Metabrik::Brik::Brik::Search:
    file: lib/Metabrik/Brik/Brik/Search.pm
  Metabrik::Brik::Core::Context:
    file: lib/Metabrik/Brik/Core/Context.pm
  Metabrik::Brik::Core::Global:
    file: lib/Metabrik/Brik/Core/Global.pm
  Metabrik::Brik::Core::Log:
    file: lib/Metabrik/Brik/Core/Log.pm
  Metabrik::Brik::Core::Shell:
    file: lib/Metabrik/Brik/Core/Shell.pm
  Metabrik::Brik::File::Find:
    file: lib/Metabrik/Brik/File/Find.pm
  Metabrik::Brik::File::Read:
    file: lib/Metabrik/Brik/File/Read.pm
  Metabrik::Brik::File::Write:
    file: lib/Metabrik/Brik/File/Write.pm
  Metabrik::Brik::Remote::Ssh2:
    file: lib/Metabrik/Brik/Remote/Ssh2.pm
  Metabrik::Brik::Shell::Command:
    file: lib/Metabrik/Brik/Shell/Command.pm
  Metabrik::Brik::Shell::History:
    file: lib/Metabrik/Brik/Shell/History.pm
  Metabrik::Brik::Shell::Rc:
    file: lib/Metabrik/Brik/Shell/Rc.pm
  Metabrik::Brik::Shell::Script:
    file: lib/Metabrik/Brik/Shell/Script.pm
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.00_04
