---
abstract: 'formerly PerL Awesome SHell, Yeeeehaaaaaa!'
author:
  - 'GomoR <gomor_at_metabrik.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Metabrik
provides:
  CPAN::Class::Gomor:
    file: lib/CPAN/Class/Gomor.pm
    version: '1.02'
  CPAN::Class::Gomor::Hash:
    file: lib/CPAN/Class/Gomor/Hash.pm
    version: '1.02'
  CPAN::Data::Dump:
    file: lib/CPAN/Data/Dump.pm
    version: '1.22'
  CPAN::Lexical::Persistence:
    file: lib/CPAN/Lexical/Persistence.pm
    version: '1.020'
  CPAN::Module::Reload:
    file: lib/CPAN/Module/Reload.pm
    version: '1.08'
  CPAN::Term::Shell:
    file: lib/CPAN/Term/Shell.pm
    version: '0.06'
  CPAN::Term::Shell::OnScopeLeave:
    file: lib/CPAN/Term/Shell.pm
    version: '0.06'
  CPAN::local::lib:
    file: lib/CPAN/local/lib.pm
    version: '2.000014'
  Metabrik:
    file: lib/Metabrik.pm
    version: 1.00_07
  Metabrik::Core::Context:
    file: lib/Metabrik/Core/Context.pm
  Metabrik::Core::Global:
    file: lib/Metabrik/Core/Global.pm
  Metabrik::Core::Log:
    file: lib/Metabrik/Core/Log.pm
  Metabrik::Core::Shell:
    file: lib/Metabrik/Core/Shell.pm
  Metabrik::File::Find:
    file: lib/Metabrik/File/Find.pm
  Metabrik::Perl::Module:
    file: lib/Metabrik/Perl/Module.pm
  Metabrik::Shell::Command:
    file: lib/Metabrik/Shell/Command.pm
  Metabrik::Shell::History:
    file: lib/Metabrik/Shell/History.pm
  Metabrik::Shell::Rc:
    file: lib/Metabrik/Shell/Rc.pm
  Metabrik::Shell::Script:
    file: lib/Metabrik/Shell/Script.pm
requires:
  Cwd: '0'
  File::Find: '0'
  File::HomeDir: '0'
  IO::All: '0'
  Term::ANSIColor: '0'
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.00_07
