---
abstract: 'formerly PerL Awesome SHell, Yeeeeaaaaaa!'
author:
  - 'GomoR <gomor-cpan_at_gomor.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.132510'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Metabricky
provides:
  Metabricky:
    file: lib/Metabricky.pm
    version: 0.94
  Metabricky::Brick:
    file: lib/Metabricky/Brick.pm
  Metabricky::Brick::Address::Netmask:
    file: lib/Metabricky/Brick/Address/Netmask.pm
  Metabricky::Brick::Audit::Dns:
    file: lib/Metabricky/Brick/Audit/Dns.pm
  Metabricky::Brick::Core::Context:
    file: lib/Metabricky/Brick/Core/Context.pm
  Metabricky::Brick::Core::Global:
    file: lib/Metabricky/Brick/Core/Global.pm
  Metabricky::Brick::Core::Log:
    file: lib/Metabricky/Brick/Core/Log.pm
  Metabricky::Brick::Crypto::Aes:
    file: lib/Metabricky/Brick/Crypto/Aes.pm
  Metabricky::Brick::Database::Cwe:
    file: lib/Metabricky/Brick/Database/Cwe.pm
  Metabricky::Brick::Database::Keystore:
    file: lib/Metabricky/Brick/Database/Keystore.pm
  Metabricky::Brick::Database::Nvd:
    file: lib/Metabricky/Brick/Database/Nvd.pm
  Metabricky::Brick::Database::Sqlite:
    file: lib/Metabricky/Brick/Database/Sqlite.pm
  Metabricky::Brick::Database::Vfeed:
    file: lib/Metabricky/Brick/Database/Vfeed.pm
  Metabricky::Brick::Encoding::Base64:
    file: lib/Metabricky/Brick/Encoding/Base64.pm
  Metabricky::Brick::Example::Template:
    file: lib/Metabricky/Brick/Example/Template.pm
  Metabricky::Brick::File::Fetch:
    file: lib/Metabricky/Brick/File/Fetch.pm
  Metabricky::Brick::File::Find:
    file: lib/Metabricky/Brick/File/Find.pm
  Metabricky::Brick::File::Read:
    file: lib/Metabricky/Brick/File/Read.pm
  Metabricky::Brick::File::Write:
    file: lib/Metabricky/Brick/File/Write.pm
  Metabricky::Brick::File::Zip:
    file: lib/Metabricky/Brick/File/Zip.pm
  Metabricky::Brick::Http::Proxy:
    file: lib/Metabricky/Brick/Http/Proxy.pm
  Metabricky::Brick::Http::Www:
    file: lib/Metabricky/Brick/Http/Www.pm
  Metabricky::Brick::Http::Wwwutil:
    file: lib/Metabricky/Brick/Http/Wwwutil.pm
  Metabricky::Brick::Identify::Ssh:
    file: lib/Metabricky/Brick/Identify/Ssh.pm
  Metabricky::Brick::Netbios::Name:
    file: lib/Metabricky/Brick/Netbios/Name.pm
  Metabricky::Brick::Network::Frame:
    file: lib/Metabricky/Brick/Network/Frame.pm
  Metabricky::Brick::Remote::Ssh2:
    file: lib/Metabricky/Brick/Remote/Ssh2.pm
  Metabricky::Brick::Remote::Tcpdump:
    file: lib/Metabricky/Brick/Remote/Tcpdump.pm
  Metabricky::Brick::Server::Agent:
    file: lib/Metabricky/Brick/Server/Agent.pm
  Metabricky::Brick::Server::Agent::Server:
    file: lib/Metabricky/Brick/Server/Agent.pm
  Metabricky::Brick::Shell::Meby:
    file: lib/Metabricky/Brick/Shell/Meby.pm
  Metabricky::Brick::Ssdp::Ssdp:
    file: lib/Metabricky/Brick/Ssdp/Ssdp.pm
  Metabricky::Brick::System::Arp:
    file: lib/Metabricky/Brick/System/Arp.pm
  Metabricky::Brick::System::Os:
    file: lib/Metabricky/Brick/System/Os.pm
  Metabricky::Brick::System::Route:
    file: lib/Metabricky/Brick/System/Route.pm
  Metabricky::Ext::Shell:
    file: lib/Metabricky/Ext/Shell.pm
  Metabricky::Ext::Utils:
    file: lib/Metabricky/Ext/Utils.pm
requires:
  Class::Gomor: 1.00
  Cwd: 0
  Data::Dump: 0
  Data::Dumper: 0
  File::Find: 0
  File::HomeDir: 0
  IO::All: 0
  IPC::Run: 0
  Lexical::Persistence: 0
  Module::Reload: 0
  Term::ANSIColor: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 0.94
